name: Auto Build and Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  release:
    name: Auto Build and Release
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.get_tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag and bump version
        id: get_tag
        run: |
          # Get the latest tag, or default to v0.0.0 if none exists
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          # Parse version components
          VERSION=${LATEST_TAG#v}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # Increment minor version
          NEW_MINOR=$((MINOR + 1))
          NEW_TAG="v${MAJOR}.${NEW_MINOR}.0"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "New tag will be: $NEW_TAG"

  build:
    name: Build for ${{ matrix.os }}
    needs: release
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            goos: linux
            goarch: amd64
            output: youtube-audio-extractor-linux-amd64
          - os: macos
            runner: macos-latest
            goos: darwin
            goarch: amd64
            output: youtube-audio-extractor-darwin-amd64
          - os: macos-arm64
            runner: macos-latest
            goos: darwin
            goarch: arm64
            output: youtube-audio-extractor-darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies (Linux)
        if: matrix.goos == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          go build -o youtube-audio-extractor -ldflags="-s -w"

      - name: Create macOS .app bundle
        if: matrix.goos == 'darwin'
        run: |
          mkdir -p "YouTube Audio Extractor.app/Contents/MacOS"
          mkdir -p "YouTube Audio Extractor.app/Contents/Resources"
          cp youtube-audio-extractor "YouTube Audio Extractor.app/Contents/MacOS/"
          cp Info.plist "YouTube Audio Extractor.app/Contents/"
          chmod +x "YouTube Audio Extractor.app/Contents/MacOS/youtube-audio-extractor"

      - name: Create zip archive (macOS)
        if: matrix.goos == 'darwin'
        run: |
          zip -r ${{ matrix.output }}.zip "YouTube Audio Extractor.app"

      - name: Create zip archive (Linux)
        if: matrix.goos == 'linux'
        run: |
          zip ${{ matrix.output }}.zip youtube-audio-extractor

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}.zip

  create-release:
    name: Create GitHub Release
    needs: [release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Display structure
        run: ls -R ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.new_tag }}
          name: Release ${{ needs.release.outputs.new_tag }}
          files: ./artifacts/**/youtube-audio-extractor-*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
